# application.yml
server:
  port: 10000

logging:
  level:
    root: info
    '[com.sh.app]': debug
    
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: spring
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
      # create - 매번 drop 후 create한다는 의미, update로 변경사항만 적용할 수 있도록 한다
      # 운영 시에는 none, validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect